# sudo required and trusty used as a hack to get a newer cmake.

# sudo: required
# dist: trusty
# language: generic

# cache:
#   apt: true


# matrix:
#   include:
#     - os: linux
#       env: CXX=g++-5 CC=gcc-5
#       addons:
#         apt:
#           packages:
#             - cmake
#             - g++-5
#           sources: &sources
#             - ubuntu-toolchain-r-test
#             - llvm-toolchain-precise-3.8
#     - os: linux
#       env: CXX=clang++-3.8 CC=clang-3.8
#       addons:
#         apt:
#           packages:
#             - cmake
#             - clang-3.8
#           sources: *sources

# # The build scripts.
# script:
#   - uname -a
#   - ulimit -a
#   - ./Configure_Make.sh
#   - cd build-make
#   - make -j2
#   - make check

# notifications:
#   email:
#     - mhop@microsoft.com
#     - aclemmer@microsoft.com
#     - danluu@microsoft.com
