# Compare output when log was generated by make-phrases.py

import csv

with open("/tmp/QueryPipelineStatistics.csv") as f:
    reader = csv.reader(f)
    header = next(reader)

    assert header == ['query',
                      'rows',
                      'matches',
                      'quadwords',
                      'cachelines',
                      'parse',
                      'plan',
                      'match']
    normal_sum  = 0
    phrase_sum = 0
    for row in reader:
        if row[0][0] == '"':
            phrase_sum += float(row[7])
        else:
            normal_sum += float(row[7])

    print("normal query time", normal_sum)
    print("phrase query time", phrase_sum)
